### ISSUE TITLE
Replace httpreq with xfetch

### ISSUE THREAD

**Issue by gajus** [fvdm/nodejs-geoip2ws#27]
`httpreq` does not implement either `debug` or `HTTP_PROXY`. Therefore, it is makes extremely tedious to debug an issue with `geoip2ws`.

I am just getting an error "API Error" without ability to either proxy the query to see whats going on or get additional debug information.

I am happy to raise a PR if you are open for a change.

**Comment by gajus** [comment]
Never mind.

Didn't see `code` and `error` properties.

That sorts it for me.

**Comment by fvdm** [comment]
Ah ok, I was already looking what could be going wrong.

Regarding xfetch, I prefer libs with the least number of dependencies possible, xfetch has way too many.

And httpreq does have HTTP proxy support, I could make it a config setting.

**Comment by gajus** [comment]
> And httpreq does have HTTP proxy support, I could make it a config setting.

It doesn't allow to set it using `HTTP_PROXY` environment variable.

**Comment by fvdm** [comment]
Yeah, but I can implement that in geoip2ws

**Comment by gajus** [comment]
> Yeah, but I can implement that in geoip2ws

I don't recommend it. It is a mix of responsibilities. Raising an issue with `httpreq` is a better move.
