### ISSUE TITLE
Module not found:

### ISSUE THREAD

**Issue by buddyff** [fvdm/nodejs-geoip2ws#28]
I installed the package as you said, but I missing these dependencies. I'm using webpack.

Module not found: Error: Can't resolve 'net' in '.../node_modules/geoip2ws'
Module not found: Error: Can't resolve 'fs' in '.../node_modules/httpreq/lib'

**Comment by fvdm** [comment]
Hi @buddyff, the `net` and `fs` dependencies are core libraries of [Node.js](https://nodejs.org) for which `geoip2ws` is intended. I don't know anything about webpack, so I'm afraid I can't help you with this.
