### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by aronsiemieniuk** [fvdm/nodejs-geoip2ws#29]
Hi,
I've been using geoip2ws for some time. It's been working great. Since October I found it having issue with cors. I don't know if something's changed in Maxmind services or it's geoip2ws causing the trouble. Now I'm using version 1.8.9. All popular browsers affected. Console output below:

`Failed to load https://geoip.maxmind.com/geoip/v2.1/country/me: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://solcdn-a.akamaihd.net' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

Of course domain **solcdn-a.akamaihd.net** has been added in Maxmind
Any help appreciated!

**Comment by fvdm** [comment]
I'm afraid I can't help you with using the geoip2ws package in a browser. I wrote it only for serverside use.

When I debug the API response from Maxmind I get no CORS related headers from them and the response data looks alright too. Do you perhaps use a proxy that could be injecting headers?

I only get these:

```js
// https://geoip.maxmind.com/geoip/v2.1/country/me
{ headers: 
   { server: 'geoip2-daemon',
     date: 'Sat, 14 Oct 2017 16:25:35 GMT',
     'content-type': 'application/vnd.maxmind.com-country+json; charset=UTF-8; version=2.1',
     'content-length': '715',
     connection: 'close' },
  statusCode: 200,
  body: // ..location data
```

**Comment by fvdm** [comment]
As there is no response I’m closing this issue.
