### ISSUE TITLE
"userId" type

### ISSUE THREAD

**Issue by GHNewbiee** [fvdm/nodejs-geoip2ws#35]
Hi,

Please clarify the type of `userId`.

In all examples it is entered as `integer`, but in the "functions" table the type is `string`.

Tia

PS: Yes, I am aware about `string` <--> `integer` (`number`) conversions.

**Comment by fvdm** [comment]
Hi @GHNewbiee, you're right it should be a string in the example. Updated the readme, thanks!

**Comment by GHNewbiee** [comment]
Also there:

> // With arguments
> const geo = require ('geoip2ws') (1234, 'abc', 'country', 2000);

'1234' instead of 1234.

**Comment by fvdm** [comment]
I'm getting tired of all those legacy use cases for such a simple tool. Version 2 will be much cleaner and have a shorter readme. 😄
