### ISSUE TITLE
Passing parameters on call (Feature request)

### ISSUE THREAD

**Issue by GHNewbiee** [fvdm/nodejs-geoip2ws#36]
Hi,

There are cases in which the parameters are **not** known from the beginning and are taken **after** querying a database. In this case, it would be more **convenient** if the parameters were passed later as an **options object** during the call and not on declaration through `require`.

Tia

**Comment by fvdm** [comment]
Hi @GHNewbiee, great idea! I'll look into it.

**Comment by fvdm** [comment]
@GHNewbiee Sorry I have forgotten about this. The change is now published to npm.

**Comment by fvdm** [comment]
Example:
```js
// init without config
const geoip = require ('geoip2ws')();

// include config in the lookup
geoip ({
  userId: 123,
  licenseKey: 'abc123',
  ip: '1.2.3.4',
  service: 'city',
})
  .then (console.log)
  .catch (console.error)
;
```
