### ISSUE TITLE
Keep Alive Option

### ISSUE THREAD

**Issue by bjaworski3** [fvdm/nodejs-geoip2ws#39]
When making large amount of Maxmind calls, it would be nice to reuse the previously opened connections instead of having to reopen them each time. This helps speed up the requests and also limits the amount of sockets opened when making requests.

Would it be possible to include an option for KeepAlive? Or just in general the various http agent settings:

https://nodejs.org/api/http.html#http_new_agent_options

**Comment by fvdm** [comment]
@bjaworski3 sorry I didn't get the notification. It's a good idea, I will look into it after new year.

**Comment by fvdm** [comment]
This requires a change in the httpreq lib
