### ISSUE TITLE
Trying to Get state name

### ISSUE THREAD

**Issue by DonRichards** [fvdm/nodejs-geoip2ws#8]
"subdivisions" throws an error(s) 

> var insights = new require ('geoip2ws') (userId, licenseKey, 'insights');
> insights ('111.111.111.111', myCallback);

> data.subdivisions.iso_code = undefined
> data.subdivisions = [object Object]
> data.subdivisions.names = undefined 
> data.subdivisions.names.en = Can't read property 'en'

Am I doing this incorrectly?

**Comment by DonRichards** [comment]
I found a work around, it looks like you added [] for some reason. 
data.subdivisions[0].names.en

**Comment by fvdm** [comment]
What does `console.log (data.subdivisions)` give you?
My code does not alter the API response, it is provided exactly as received.

**Comment by DonRichards** [comment]
I listed the outputs above. Output is this.
> [object Object]

**Comment by oschwald** [comment]
Subdivisions is [an array](http://dev.maxmind.com/geoip/geoip2/web-services/#subdivisions). There can be multiple levels of ISO subdivisions for some countries.

**Comment by fvdm** [comment]
Indeed, subdivisions is an array or not available (undefined). When it is available the last element is _usually_ the state, depending on region.

```js
function getState (data) {
  if (Array.isArray (data.subdivisions)) {
    return data.subdivisions[data.subdivisions.length -1].names.en;
  }
  return null;
}

insights ('129.67.242.154', function (err, data) {
  if (err) { return console.log (err); }
  console.log ('State: %s', getState (data));
});
```

**Comment by oschwald** [comment]
In many countries, such as the US, there is only one subdivision level, corresponding to states. However, some countries such as the United Kingdom have multiple levels, e.g., [0] England, [1] Oxfordshire. The subdivisions are always largest to smallest.

**Comment by DonRichards** [comment]
That makes using this kinda messy. If statements could be endless with this logic. I didn't notice the documentation stating this. Is there a more descriptive rundown on this somewhere?

**Comment by fvdm** [comment]
Not that I know of. I'm affraid there is no easier solution as each region have their [own system](http://geography.about.com/od/politicalgeography/a/countrydivision.htm).

**Comment by oschwald** [comment]
The [MaxMind GeoIP2 JavaScript API](http://dev.maxmind.com/geoip/geoip2/javascript/) adds in an empty array if it doesn't exist as well as adding a `most_specific_subdivision` property that returns the last element in the array. Maybe something similar could be done with this API.

**Comment by fvdm** [comment]
Alright, it's on npm :)
Thanks for the hint @oschwald
