### ISSUE TITLE
Client side usage

### ISSUE THREAD

**Issue by Jon-Biz** [fvdm/nodejs-geoip2ws#9]
Hi, 

I'm trying to setup a client side call to the maxmind API using a `browserify` based build. Being unfamiliar with the Maxmind api, I was wondering if there is a way to call use this module to call their service without knowing one's ip address, as you can with the client side library. 

I'm trying not to have to insert their script as a global, since it will complicate our build process.

thanks kindly!

**Comment by Jon-Biz** [comment]
Never mind. I just cut and pasted their client side library into my code ;)

**Comment by Jon-Biz** [comment]
I found a better solution: #10

**Comment by fvdm** [comment]
I didn't know about `me`, clever trick. Thanks for the suggestion!

**Comment by Jon-Biz** [comment]
:+1:

**Comment by Jon-Biz** [comment]
Might want to make a mention of it in the README, and that it's now client side compatible :)

**Comment by fvdm** [comment]
If I make browser support official in the readme I need to include scripted tests, but so far I have not found a stable headless solution with a small footprint.
